version: "3.7"
services:
  app:
    build:
      args:
        user: agustin
        uid: 997
      context: ./
      dockerfile: Dockerfile
    image: mechanicsheep
    container_name: mechanicsheep-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mechanicsheep

  db:
    image: mysql:5.7
    container_name: mechanicsheep-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 8179:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - mechanicsheep

  nginx:
    image: nginx:alpine
    container_name: mechanicsheep-nginx
    restart: unless-stopped
    ports:
      - 8196:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mechanicsheep

  adminer:
    image: adminer
    container_name: mechanicsheep-db-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - mechanicsheep


networks:
  mechanicsheep:
    driver: bridge
